prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    additionalScrapeConfigs:
      - job_name: 'istio-envoy'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: [default, istio-system]  
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: "true"
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: "http-envoy-prom"
          - target_label: __address__
            replacement: "${1}:15090"
            source_labels: [__meta_kubernetes_pod_ip]

defaultRules:
  create: true
  rules:
    istio: true

namespaceSelectors:
  - matchNames:
      - default
      - istio-system
      - monitoring